// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV7YilCPefTvYbjj378blKogym4po8RJk',
    appId: '1:503914200184:web:d2488cadeab17ab062c18d',
    messagingSenderId: '503914200184',
    projectId: 'app-de-teste-d5641',
    authDomain: 'app-de-teste-d5641.firebaseapp.com',
    databaseURL: 'https://app-de-teste-d5641.firebaseio.com',
    storageBucket: 'app-de-teste-d5641.firebasestorage.app',
    measurementId: 'G-YBD0NMHP2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7DWUTfllQ1mR2qeUqu6NqQ_821Ryu3e4',
    appId: '1:503914200184:android:e1d9151faace296862c18d',
    messagingSenderId: '503914200184',
    projectId: 'app-de-teste-d5641',
    databaseURL: 'https://app-de-teste-d5641.firebaseio.com',
    storageBucket: 'app-de-teste-d5641.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV7YilCPefTvYbjj378blKogym4po8RJk',
    appId: '1:503914200184:web:35c7900f1c4c5a4a62c18d',
    messagingSenderId: '503914200184',
    projectId: 'app-de-teste-d5641',
    authDomain: 'app-de-teste-d5641.firebaseapp.com',
    databaseURL: 'https://app-de-teste-d5641.firebaseio.com',
    storageBucket: 'app-de-teste-d5641.firebasestorage.app',
    measurementId: 'G-RRF208H10B',
  );
}
